spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL8Dialect
  sql:
    init:
      mode: never

  redis:
    host: redis
    port: 6379
    password:
